from alembic import op
import sqlalchemy as sa
revision='0001'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('users',sa.Column('id',sa.String(36),primary_key=True),sa.Column('username',sa.String(64),unique=True,nullable=False),sa.Column('email',sa.String(255),unique=True),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('display_name',sa.String(128)),sa.Column('is_active',sa.Boolean,nullable=False,default=True),sa.Column('failed_login_count',sa.Integer,nullable=False,default=0),sa.Column('locked_until',sa.DateTime),sa.Column('last_login_at',sa.DateTime),sa.Column('created_at',sa.DateTime,nullable=False),sa.Column('updated_at',sa.DateTime),sa.Column('created_by',sa.String(36),sa.ForeignKey('users.id')))
    op.create_table('roles',sa.Column('id',sa.String(36),primary_key=True),sa.Column('code',sa.String(32),unique=True,nullable=False),sa.Column('name',sa.String(64),nullable=False),sa.Column('description',sa.String(255)))
    op.create_table('permissions',sa.Column('id',sa.String(36),primary_key=True),sa.Column('code',sa.String(64),unique=True,nullable=False),sa.Column('name',sa.String(128),nullable=False),sa.Column('category',sa.String(32)),sa.Column('description',sa.String(255)))
    op.create_table('user_roles',sa.Column('user_id',sa.String(36),sa.ForeignKey('users.id'),primary_key=True),sa.Column('role_id',sa.String(36),sa.ForeignKey('roles.id'),primary_key=True),sa.Column('assigned_by',sa.String(36),sa.ForeignKey('users.id')),sa.Column('assigned_at',sa.DateTime,nullable=False))
    op.create_table('role_permissions',sa.Column('role_id',sa.String(36),sa.ForeignKey('roles.id'),primary_key=True),sa.Column('permission_id',sa.String(36),sa.ForeignKey('permissions.id'),primary_key=True))
    op.create_table('refresh_tokens',sa.Column('id',sa.String(36),primary_key=True),sa.Column('user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('jti',sa.String(36),unique=True,nullable=False),sa.Column('token_hash',sa.String(255),nullable=False),sa.Column('expires_at',sa.DateTime,nullable=False),sa.Column('revoked',sa.Boolean,nullable=False,default=False),sa.Column('created_at',sa.DateTime,nullable=False),sa.Column('revoked_at',sa.DateTime),sa.Column('replaced_by',sa.String(36)))
    op.create_table('audit_log',sa.Column('id',sa.String(36),primary_key=True),sa.Column('actor_user_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('action',sa.String(64),nullable=False),sa.Column('target_type',sa.String(64)),sa.Column('target_id',sa.String(36)),sa.Column('detail',sa.JSON),sa.Column('created_at',sa.DateTime,nullable=False))
def downgrade():
    for name in ('audit_log','refresh_tokens','role_permissions','user_roles','permissions','roles','users'): op.drop_table(name)
