from alembic import op
import sqlalchemy as sa

revision = '0002_catalog_template_versioning'
down_revision = '0001'
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('software', sa.Column('id',sa.String(36),primary_key=True), sa.Column('code',sa.String(64),nullable=False), sa.Column('name',sa.String(128),nullable=False), sa.Column('version',sa.String(64)), sa.Column('status',sa.String(20),nullable=False), sa.Column('created_at',sa.DateTime,nullable=False), sa.Column('updated_at',sa.DateTime), sa.UniqueConstraint('code',name='uq_software_code'))
    op.create_table('profiles', sa.Column('id',sa.String(36),primary_key=True), sa.Column('software_id',sa.String(36),sa.ForeignKey('software.id'),nullable=False), sa.Column('code',sa.String(64),nullable=False), sa.Column('name',sa.String(128),nullable=False), sa.Column('status',sa.String(20),nullable=False), sa.Column('created_at',sa.DateTime,nullable=False), sa.Column('updated_at',sa.DateTime), sa.UniqueConstraint('software_id','code',name='uq_profile_software_code'))
    op.create_table('data_templates', sa.Column('id',sa.String(36),primary_key=True), sa.Column('code',sa.String(64),nullable=False), sa.Column('name',sa.String(128),nullable=False), sa.Column('description',sa.String(500)), sa.Column('status',sa.String(20),nullable=False), sa.Column('created_by',sa.String(36),sa.ForeignKey('users.id')), sa.Column('revision',sa.Integer,nullable=False), sa.Column('created_at',sa.DateTime,nullable=False), sa.Column('updated_at',sa.DateTime), sa.UniqueConstraint('code',name='uq_data_template_code'))
    op.create_table('template_versions', sa.Column('id',sa.String(36),primary_key=True), sa.Column('template_id',sa.String(36),sa.ForeignKey('data_templates.id'),nullable=False), sa.Column('version_no',sa.Integer,nullable=False), sa.Column('status',sa.String(20),nullable=False), sa.Column('schema_json',sa.JSON,nullable=False), sa.Column('created_by',sa.String(36),sa.ForeignKey('users.id')), sa.Column('published_by',sa.String(36),sa.ForeignKey('users.id')), sa.Column('revision',sa.Integer,nullable=False), sa.Column('created_at',sa.DateTime,nullable=False), sa.Column('published_at',sa.DateTime), sa.UniqueConstraint('template_id','version_no',name='uq_template_version'), sa.CheckConstraint('revision >= 1',name='ck_template_version_revision'))
    op.create_table('template_fields', sa.Column('id',sa.String(36),primary_key=True), sa.Column('template_version_id',sa.String(36),sa.ForeignKey('template_versions.id'),nullable=False), sa.Column('path',sa.String(255),nullable=False), sa.Column('label',sa.String(128),nullable=False), sa.Column('data_type',sa.String(32),nullable=False), sa.Column('unit',sa.String(32)), sa.Column('required',sa.Boolean,nullable=False), sa.Column('rules_json',sa.JSON,nullable=False), sa.Column('source_mapping_json',sa.JSON,nullable=False), sa.Column('ordinal',sa.Integer,nullable=False), sa.UniqueConstraint('template_version_id','path',name='uq_template_field_path'))
    op.create_table('source_snapshots', sa.Column('id',sa.String(36),primary_key=True), sa.Column('source_id',sa.String(255),nullable=False), sa.Column('source_revision',sa.String(128)), sa.Column('content_hash',sa.String(128),nullable=False), sa.Column('raw_payload',sa.JSON,nullable=False), sa.Column('status',sa.String(20),nullable=False), sa.Column('captured_at',sa.DateTime,nullable=False), sa.Column('created_by',sa.String(36),sa.ForeignKey('users.id')), sa.UniqueConstraint('source_id','source_revision','content_hash',name='uq_source_snapshot'))
    op.create_table('data_versions', sa.Column('id',sa.String(36),primary_key=True), sa.Column('version_no',sa.Integer,nullable=False), sa.Column('revision',sa.Integer,nullable=False), sa.Column('status',sa.String(20),nullable=False), sa.Column('source_snapshot_id',sa.String(36),sa.ForeignKey('source_snapshots.id')), sa.Column('template_version_id',sa.String(36),sa.ForeignKey('template_versions.id')), sa.Column('checksum',sa.String(128),nullable=False), sa.Column('record_count',sa.Integer,nullable=False), sa.Column('created_by',sa.String(36),sa.ForeignKey('users.id')), sa.Column('approved_by',sa.String(36),sa.ForeignKey('users.id')), sa.Column('published_by',sa.String(36),sa.ForeignKey('users.id')), sa.Column('failure_code',sa.String(64)), sa.Column('failure_detail',sa.JSON), sa.Column('created_at',sa.DateTime,nullable=False), sa.Column('approved_at',sa.DateTime), sa.Column('published_at',sa.DateTime), sa.UniqueConstraint('version_no',name='uq_data_version_no'), sa.CheckConstraint('version_no >= 1',name='ck_data_version_no'), sa.CheckConstraint('record_count >= 0',name='ck_data_version_count'))
    op.create_table('performance_records', sa.Column('id',sa.String(36),primary_key=True), sa.Column('stable_key',sa.String(512),nullable=False), sa.Column('software_id',sa.String(36),sa.ForeignKey('software.id'),nullable=False), sa.Column('profile_id',sa.String(36),sa.ForeignKey('profiles.id'),nullable=False), sa.Column('template_version_id',sa.String(36),sa.ForeignKey('template_versions.id'),nullable=False), sa.Column('owner_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False), sa.Column('lifecycle_status',sa.String(24),nullable=False), sa.Column('draft_payload',sa.JSON,nullable=False), sa.Column('rejection_reason',sa.String(1000)), sa.Column('revision',sa.Integer,nullable=False), sa.Column('deleted',sa.Boolean,nullable=False), sa.Column('deleted_at',sa.DateTime), sa.Column('created_at',sa.DateTime,nullable=False), sa.Column('updated_at',sa.DateTime,nullable=False), sa.UniqueConstraint('stable_key',name='uq_performance_record_stable_key'), sa.CheckConstraint('revision >= 1',name='ck_record_revision'))
    op.create_table('performance_record_versions', sa.Column('id',sa.String(36),primary_key=True), sa.Column('record_id',sa.String(36),sa.ForeignKey('performance_records.id'),nullable=False), sa.Column('data_version_id',sa.String(36),sa.ForeignKey('data_versions.id'),nullable=False), sa.Column('record_revision',sa.Integer,nullable=False), sa.Column('raw_payload',sa.JSON,nullable=False), sa.Column('parsed_payload',sa.JSON,nullable=False), sa.Column('derived_payload',sa.JSON,nullable=False), sa.Column('source_snapshot_id',sa.String(36),sa.ForeignKey('source_snapshots.id')), sa.Column('source_locator',sa.String(512)), sa.Column('created_at',sa.DateTime,nullable=False), sa.UniqueConstraint('data_version_id','record_id',name='uq_record_version'))
    op.create_table('catalog_heads', sa.Column('scope_key',sa.String(64),primary_key=True), sa.Column('current_version_id',sa.String(36),sa.ForeignKey('data_versions.id')), sa.Column('current_revision',sa.Integer,nullable=False), sa.Column('updated_at',sa.DateTime,nullable=False))
    op.execute("INSERT INTO catalog_heads (scope_key,current_revision,updated_at) VALUES ('performance_catalog',0,CURRENT_TIMESTAMP)")
    with op.batch_alter_table('audit_log') as batch:
        batch.add_column(sa.Column('target_revision',sa.Integer))
        batch.add_column(sa.Column('request_id',sa.String(64)))
        batch.add_column(sa.Column('before_json',sa.JSON))
        batch.add_column(sa.Column('after_json',sa.JSON))
        batch.add_column(sa.Column('ip_address',sa.String(64)))
        batch.add_column(sa.Column('user_agent',sa.String(512)))
        batch.add_column(sa.Column('outcome',sa.String(20)))

def downgrade():
    with op.batch_alter_table('audit_log') as batch:
        for col in ('outcome','user_agent','ip_address','after_json','before_json','request_id','target_revision'): batch.drop_column(col)
    for table in ('catalog_heads','performance_record_versions','performance_records','data_versions','source_snapshots','template_fields','template_versions','data_templates','profiles','software'): op.drop_table(table)
