"""Adapter protocol for external tabular data sources."""
from typing import Protocol
from app.db.models import DataSource

class DataSourceAdapter(Protocol):
    async def discover(self, source: DataSource) -> dict: ...
    async def fetch_snapshot(self, source: DataSource, sheet_id: str) -> dict: ...
    async def health_check(self, source: DataSource) -> dict: ...
